# Site
repository: your-git-repository-name

# Content configuration version
version: 2

# Personal info
name: Sebasti치n Marcelo Forische Su치rez
title: Software Developer
email: sforische@gmail.com
phone: +598 91286606

# Dark Mode (true/false/never)
darkmode: false

# About Section
about_profile_image: Sebastian Forische.jpg
about_content: | 
  I am an enthusiastic and driven computer science professional with a deep passion for technology. 
  I strive to make meaningful contributions by leveraging my skills in communication, teamwork, and technical expertise 
  to solve complex challenges and drive innovation. I am currently pursuing a degree in Computer Engineering at Universidad Cat칩lica del Uruguay and have experience in cybersecurity and full-stack development.


- title: Experience
    layout: list
    content:
      - layout: left
        title: BASF Services Americas
        sub_title: Automation Developer
        caption: 2022 - Present
        quote: >
          Automation and application development in O2C Technology Experts
        description: | 
          - Automation and application development in O2C Technology Experts.
          - Created a program using Awilix and Axios to authenticate and consume multiple REST APIs.
          - Developed applications following SOLID principles and leveraging design patterns to ensure scalability and maintainability.
          - Designed and implemented database solutions for process automation projects.
          - Collaborated with cross-functional teams to identify and solve complex technical challenges.


      - layout: left
        title: CIEMSA
        sub_title: Full Stack Developer
        caption: April 2023 - July 2023
        quote: >
          Full stack development for municipal radar applications.
        description: | 
            Developed and maintained web and desktop applications for the Municipality of Montevideo, ensuring efficient and reliable performance.
    

  - title: Education
    layout: list
    content:
      - layout: left
        title: Universidad Cat칩lica del Uruguay
        sub_title: Bachelor's in Computer Engineering
        caption: 2020 - Present
        description: | 
            Pursuing a Bachelor's in the fourth year of the degree in Computer Engineering, with a focus on software development, systems, and cybersecurity.

      - layout: left
        title: BIOS Institute
        sub_title: Cybersecurity Technician
        caption: 2021 - 2022
        description: |
              Completed a Cybersecurity Technician program, gaining practical knowledge in penetration testing and system security.
         

  - title: Core Skills
    layout: list
    content:
      - layout: left
        title: Programming
        description: |
          - C#, Python, HTML, CSS, JavaScript (Node.js), Shell Script, TypeScript (Angular).
          - Experience with REST APIs, Awilix, and Axios.
          - Advanced Excel macros with VBA.
          - Penetration testing using Kali Linux.
          - Experience with Azure and Azure DevOps.
          - Database management and design (SQL, NoSQL).
          - Application design following SOLID principles and design patterns.
          - Cloud server management (Azure,).
          - Container management with Docker and orchestration with Kubernetes.
          - Configuration of virtual private networks (VPNs) and Firewalls.
          - Knowledge of load balancing and auto-scaling services in the cloud.
          - Management of authentication and authorization (OAuth, LDAP, Active Directory).

  - title: A Little More About Me
    layout: text
    content: | 
      I enjoy exploring new technologies and have a strong interest in cybersecurity, cloud computing, and software development. I am passionate about creating scalable and maintainable solutions while always learning and improving my skills.

# Footer
footer_show_references: true

# Build settings
sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
]

